const pokemons = [
  // Bulbasaur
  {
    pokedex_number: 1,
    name: 'Bulbasaur',
    image_url: '/pokemon/Bulbasaur.png',
    description: "Una rara semilla fue plantada en su espalda al nacer. La planta brota y crece con este Pokémon.",
    type_1: 'planta',
    type_2: 'veneno',
    ps: 45,
    attack: 49,
    defense: 49,
    special_attack: 65,
    special_defense: 65,
    speed: 45,
    pre_evolution: null,
    evolution: 2
  },
  // Ivysaur
  {
    pokedex_number: 2,
    name: 'Ivysaur',
    image_url: '/pokemon/Ivysaur.png',
    description: "Cuando el bulbo de su espalda crece, parece no poder ponerse de pie sobre sus patas traseras.",
    type_1: 'planta',
    type_2: 'veneno',
    ps: 60,
    attack: 62,
    defense: 63,
    special_attack: 80,
    special_defense: 80,
    speed: 60,
    pre_evolution: 1,
    evolution: 3
  },
  // Venusaur
  {
    pokedex_number: 3,
    name: 'Venusaur',
    image_url: '/pokemon/Venusaur.png',
    description: "La planta florece cuando absorbe energía solar. Ésta le obliga a ponerse en busca de la luz solar.",
    type_1: 'planta',
    type_2: 'veneno',
    ps: 80,
    attack: 82,
    defense: 83,
    special_attack: 100,
    special_defense: 100,
    speed: 80,
    pre_evolution: 2,
    evolution: null
  },
  // Charmander
  {
    pokedex_number: 4,
    name: 'Charmander',
    image_url: '/pokemon/Charmander.png',
    description: "Prefiere los sitios calientes. Dicen que cuando llueve sale vapor de la punta de su cola.",
    type_1: 'fuego',
    type_2: null,
    ps: 39,
    attack: 52,
    defense: 43,
    special_attack: 60,
    special_defense: 50,
    speed: 65,
    pre_evolution: null,
    evolution: 5
  },
  // Charmeleon
  {
    pokedex_number: 5,
    name: 'Charmeleon',
    image_url: '/pokemon/Charmeleon.png',
    description: "	Cuando balancea su ardiente cola, eleva la temperatura a niveles muy altos.",
    type_1: 'fuego',
    type_2: null,
    ps: 58,
    attack: 64,
    defense: 58,
    special_attack: 80,
    special_defense: 65,
    speed: 80,
    pre_evolution: 4,
    evolution: 6
  },
  // Charizard
  {
    pokedex_number: 6,
    name: 'Charizard',
    image_url: '/pokemon/Charizard.png',
    description: "Escupe fuego tan caliente que funde las rocas. Causa incendios forestales sin querer.",
    type_1: 'fuego',
    type_2: "volador",
    ps: 78,
    attack: 84,
    defense: 78,
    special_attack: 109,
    special_defense: 85,
    speed: 100,
    pre_evolution: 5,
    evolution: null
  },
  // Squirtle
  {
    pokedex_number: 7,
    name: 'Squirtle',
    image_url: '/pokemon/Squirtle.png',
    description: "Tras nacer, su espalda se hincha y endurece como una concha. Echa potente espuma por la boca.",
    type_1: 'agua',
    type_2: null,
    ps: 44,
    attack: 48,
    defense: 65,
    special_attack: 50,
    special_defense: 64,
    speed: 43,
    pre_evolution: null,
    evolution: 8
  },
  // Wartortle
  {
    pokedex_number: 8,
    name: 'Wartortle',
    image_url: '/pokemon/Wartortle.png',
    description: "Se oculta en el agua para cazar a sus presas. Al nadar ráppokedex_numberamente, mueve sus orejas para nivelarse.",
    type_1: 'agua',
    type_2: null,
    ps: 59,
    attack: 63,
    defense: 80,
    special_attack: 65,
    special_defense: 80,
    speed: 58,
    pre_evolution:  7,
    evolution: 9
  },
  // Blastoise
  {
    pokedex_number: 9,
    name: 'Blastoise',
    image_url: '/pokemon/Blastoise.png',
    description: "Un brutal Pokémon con reactores de agua en su caparazón. Éstos son usados para ráppokedex_numberos placajes.",
    type_1: 'agua',
    type_2: null,
    ps: 79,
    attack: 83,
    defense: 100,
    special_attack: 85,
    special_defense: 105,
    speed: 78,
    pre_evolution: 8,
    evolution: null
  },
  // Caterpie
  {
    pokedex_number: 10,
    name: 'Caterpie',
    image_url: '/pokemon/Caterpie.png',
    description: "Sus cortas patas están recubiertas de ventosas que le permiten subir incansable por muros y cuestas.",
    type_1: 'bicho',
    type_2: null,
    ps: 45,
    attack: 30,
    defense: 35,
    special_attack: 20,
    special_defense: 20,
    speed: 45,
    pre_evolution:  null,
    evolution: 11
  },
  // Metapod
  {
    pokedex_number: 11,
    name: 'Metapod',
    image_url: '/pokemon/Metapod.png',
    description: "Este Pokémon es vulnerable al ataque cuando su concha es blanda, dejando expuesto su frágil cuerpo.",
    type_1: 'bicho',
    type_2: null,
    ps: 50,
    attack: 20,
    defense: 55,
    special_attack: 25,
    special_defense: 25,
    speed: 30,
    pre_evolution: 10,
    evolution: 12
  },
  // Butterfree
  {
    pokedex_number: 12,
    name: 'Butterfree',
    image_url: '/pokemon/Butterfree.png',
    description: "En combate, aletea a gran velocpokedex_numberad para lanzar al aire sus tóxicos polvillos.",
    type_1: 'bicho',
    type_2: "volador",
    ps: 60,
    attack: 45,
    defense: 50,
    special_attack: 90,
    special_defense: 80,
    speed: 70,
    pre_evolution: 11,
    evolution: null
  },
  // Weedle
  {
    pokedex_number: 13,
    name: 'Weedle',
    image_url: '/pokemon/Weedle.png',
    description: "Fácil de ver por los bosques comiendo hojas. Tiene un aguijón venenoso en la cabeza.",
    type_1: 'bicho',
    type_2: "veneno",
    ps: 40,
    attack: 35,
    defense: 30,
    special_attack: 20,
    special_defense: 20,
    speed: 50,
    pre_evolution: null,
    evolution: 14
  },
  // Kakuna
  {
    pokedex_number: 14,
    name: 'Kakuna',
    image_url: '/pokemon/Kakuna.png',
    description: "Casi incapaz de moverse, este Pokémon sólo puede endurecer su caparazón para protegerse.",
    type_1: 'bicho',
    type_2: "veneno",
    ps: 45,
    attack: 25,
    defense: 50,
    special_attack: 25,
    special_defense: 25,
    speed: 35,
    pre_evolution: 13,
    evolution: 15
  },
  // Beedrill
  {
    pokedex_number: 15,
    name: 'Beedrill',
    image_url: '/pokemon/Beedrill.png',
    description: "Vuela muy deprisa y ataca con los venenosos y grandes aguijones de su cola y patas delanteras.",
    type_1: 'bicho',
    type_2: "veneno",
    ps: 65,
    attack: 90,
    defense: 40,
    special_attack: 45,
    special_defense: 80,
    speed: 75,
    pre_evolution: 14,
    evolution: null
  },
  // Pidgey
  {
    pokedex_number: 16,
    name: 'Pidgey',
    image_url: '/pokemon/Pidgey.png',
    description: "Muy común en bosques y selvas. Aletea al nivel del suelo para levantar la gravilla.",
    type_1: 'normal',
    type_2: "volador",
    ps: 40,
    attack: 45,
    defense: 40,
    special_attack: 35,
    special_defense: 35,
    speed: 56,
    pre_evolution: null,
    evolution: 17
  },
  // Pidgeotto
  {
    pokedex_number: 17,
    name: 'Pidgeotto',
    image_url: '/pokemon/Pidgeotto.png',
    description: "Muy protector de su amplio territorio, este Pokémon picoteará ferozmente a todo intruso.",
    type_1: 'normal',
    type_2: "volador",
    ps: 63,
    attack: 60,
    defense: 55,
    special_attack: 50,
    special_defense: 50,
    speed: 71,
    pre_evolution: 16,
    evolution: 18
  },
  // Pidgeot
  {
    pokedex_number: 18,
    name: 'Pidgeot',
    image_url: '/pokemon/Pidgeot.png',
    description: "Cuando caza, vuela muy deprisa a ras del agua, y sorprende a inocentes presas como Magikarp.",
    type_1: 'normal',
    type_2: "volador",
    ps: 83,
    attack: 80,
    defense: 75,
    special_attack: 70,
    special_defense: 70,
    speed: 101,
    pre_evolution: 17,
    evolution: null
  },
  // Rattata
  {
    pokedex_number: 19,
    name: 'Rattata',
    image_url: '/pokemon/Rattata.png',
    description: "Cuando ataca lo muerde todo. Pequeño y muy rápido, es muy fácil de ver en muchos sitios.",
    type_1: 'normal',
    type_2: null,
    ps: 30,
    attack: 56,
    defense: 35,
    special_attack: 25,
    special_defense: 35,
    speed: 72,
    pre_evolution: null,
    evolution: 20
  },
  // Raticate
  {
    pokedex_number: 20,
    name: 'Raticate',
    image_url: '/pokemon/Raticate.png',
    description: "Cuando ataca lo muerde todo. Pequeño y muy rápido, es muy fácil de ver en muchos sitios.",
    type_1: 'normal',
    type_2: null,
    ps: 55,
    attack: 81,
    defense: 60,
    special_attack: 50,
    special_defense: 70,
    speed: 97,
    pre_evolution: 19,
    evolution: null
  },
  // Spearow
  {
    pokedex_number: 21,
    name: 'Spearow',
    image_url: '/pokemon/Spearow.png',
    description: "Come bichos en zona de hierba. Agita sus cortas alas muy rápido para mantenerse en el aire.",
    type_1: 'normal',
    type_2: "volador",
    ps: 40,
    attack: 60,
    defense: 30,
    special_attack: 31,
    special_defense: 31,
    speed: 70,
    pre_evolution: null,
    evolution: 22
  },
  // Fearow
  {
    pokedex_number: 22,
    name: 'Fearow',
    image_url: '/pokemon/Fearow.png',
    description: "Con sus enormes y magníficas alas, puede seguir volando sin tener que aterrizar para descansar.",
    type_1: 'normal',
    type_2: "volador",
    ps: 65,
    attack: 90,
    defense: 65,
    special_attack: 61,
    special_defense: 61,
    speed: 100,
    pre_evolution: 21,
    evolution: null
  },
  // Ekans
  {
    pokedex_number: 23,
    name: 'Ekans',
    image_url: '/pokemon/Ekans.png',
    description: "Es muy silencioso y sigiloso. Come huevos de pájaros como los de Pidgey y Spearow.",
    type_1: 'veneno',
    type_2: null,
    ps: 35,
    attack: 60,
    defense: 44,
    special_attack: 40,
    special_defense: 54,
    speed: 55,
    pre_evolution: null,
    evolution: 24
  },
  // Arbok
  {
    pokedex_number: 24,
    name: 'Arbok',
    image_url: '/pokemon/Arbok.png',
    description: "Se dice que las feroces señales de alerta de su panza difieren de un área a otra.",
    type_1: 'veneno',
    type_2: null,
    ps: 60,
    attack: 85,
    defense: 69,
    special_attack: 65,
    special_defense: 79,
    speed: 80,
    pre_evolution: 23,
    evolution: null
  },
  // Pikachu
  {
    pokedex_number: 25,
    name: 'Pikachu',
    image_url: '/pokemon/Pikachu.png',
    description: "Cuando varios de estos Pokémon se juntan, su energía puede causar fuertes tormentas.",
    type_1: 'eléctrico',
    type_2: null,
    ps: 35,
    attack: 55,
    defense: 40,
    special_attack: 50,
    special_defense: 50,
    speed: 90,
    pre_evolution: null,
    evolution: 26
  },
  // Raichu
  {
    pokedex_number: 26,
    name: 'Raichu',
    image_url: '/pokemon/Raichu.png',
    description: "Su larga cola le sirve para protegerse a sí mismo de su potente y alto voltaje.",
    type_1: 'eléctrico',
    type_2: null,
    ps: 60,
    attack: 90,
    defense: 55,
    special_attack: 90,
    special_defense: 80,
    speed: 110,
    pre_evolution: 25,
    evolution: null
  }
];

module.exports = {
  pokemons
};
